
name: Build & Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: npm install
        run: npm i
      - name: ts check
        run: ./node_modules/.bin/tsc --noEmit
      - name: lint
        run: npm run lint
      - name: tests
        run: npm run test
      - name: build succeeds
        run: npm run build:pika
